// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxuzeedgbpzurfxjvmgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54dXplZWRnYnB6dXJmeGp2bWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTc5NzUsImV4cCI6MjA1OTYzMzk3NX0.s5R0VJN4XNkPQL_Oq_beece15rdKw-AhnPRFYJIMnyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);